name: 'eh-deploy-action'
description: 'This action triggers a deployment workflow'
author: 'hpsony94'
branding:
  icon: 'play'
  color: 'blue'
inputs:
  app_name:
    description: "Deployment name"
    required: true
  image_name:
    description: "Container image registry"
    required: true
  cluster_context:
    description: "Cluster context <staging>/<integration>/<production>"
    required: true
  author:
    description: "Author of deployment"
    required: false
  deploy_token:
    description: "Token of deployment"
    required: true
  trigger_deploy:
    description: "Trigger deployment"
    required: true
  wait_deploy:
    description: "Check deployment is totally rolled out"
    required: false
  wait_interval:
    description: "The number of seconds delay between checking for result of run."
    required: false
  
outputs:
  result:
    description: result

runs:
  using: 'docker'
  image: 'Dockerfile'
