name: 'deploy-action'
description: 'This action triggers a deployment workflow'
author: 'hpsony94'
branding:
  icon: 'twitter'
  color: 'blue'
inputs:
  app_name:
    description: "Deployment name"
    required: true
    default: 'employment-hero'
  image_name:
    description: "Container image registry"
    required: true
    default: 'ehdevops/example:1.0.0'
  cluster_context:
    description: "Cluster context <staging>/<intergration>/<production>"
    required: true
    default: ''
  author:
    description: "Author of deployment"
    required: true
    default: 'eh-bot'
  check:
    description: "Author of deployment"
    required: true
    default: false
  
outputs:
  result:
    description: result

runs:
  using: 'docker'
  image: 'Dockerfile'
