name: Build

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    paths-ignore:
      - '**.md'
    branches:
      - master
    tags:
      - v**

jobs:
  build-docker:
    name: Build docker image
    runs-on: ci-general
    steps:
    - uses: actions/checkout@v3
    - name: Generate Docker meta names
      uses: docker/metadata-action@v3
      id: meta
      with:
        images: thinkei/bump-it-action
        tags: |
          type=ref,event=tag
          type=raw,enable=${{ !startsWith(github.ref, 'refs/tags/') }},value=master

  actions_self-test:
    name: Run self-test for actions
    runs-on: ci-general
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: self
        id: self
        with:
          app_name: "tbd"
          image_name: "tbd"
          cluster_context: staging
          check: false
